# Generated by Django 5.0.4 on 2024-05-02 10:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=core.models.generate_uuid, max_length=100),
        ),
    ]
