# Generated by Django 5.0.4 on 2024-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
