# Generated by Django 5.0.4 on 2024-05-02 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vendor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last_login'),
            preserve_default=False,
        ),
    ]
